exports.abilities = [ [] , ["Overgrow"] ,
["Overgrow"] ,
["Overgrow"] ,
["Blaze"] ,
["Blaze"] ,
["Blaze"] ,
["Torrent"] ,
["Torrent"] ,
["Torrent"] ,
["Shield Dust"] ,
["Shed Skin"] ,
["Compound Eyes"] ,
["Shield Dust"] ,
["Shed Skin"] ,
["Swarm"] ,
["Keen Eye", "Tangled Feet"] ,
["Keen Eye", "Tangled Feet"] ,
["Keen Eye", "Tangled Feet"] ,
["Run Away", "Guts"] ,
["Run Away", "Guts"] ,
["Keen Eye"] ,
["Keen Eye"] ,
["Intimidate", "Shed Skin"] ,
["Intimidate", "Shed Skin"] ,
["Static"] ,
["Static"] ,
["Sand Veil"] ,
["Sand Veil"] ,
["Poison Point", "Rivalry"] ,
["Poison Point", "Rivalry"] ,
["Poison Point", "Rivalry"] ,
["Poison Point", "Rivalry"] ,
["Poison Point", "Rivalry"] ,
["Poison Point", "Rivalry"] ,
["Cute Charm", "Magic Guard"] ,
["Cute Charm", "Magic Guard"] ,
["Flash Fire"] ,
["Flash Fire"] ,
["Cute Charm", "Competitive"] ,
["Cute Charm", "Competitive"] ,
["Inner Focus"] ,
["Inner Focus"] ,
["Chlorophyll"] ,
["Chlorophyll"] ,
["Chlorophyll"] ,
["Effect Spore", "Dry Skin"] ,
["Effect Spore", "Dry Skin"] ,
["Compound Eyes", "Tinted Lens"] ,
["Shield Dust", "Tinted Lens"] ,
["Sand Veil", "Arena Trap"] ,
["Sand Veil", "Arena Trap"] ,
["Pickup", "Technician"] ,
["Limber", "Technician"] ,
["Damp", "Cloud Nine"] ,
["Damp", "Cloud Nine"] ,
["Vital Spirit", "Anger Point"] ,
["Vital Spirit", "Anger Point"] ,
["Intimidate", "Flash Fire"] ,
["Intimidate", "Flash Fire"] ,
["Water Absorb", "Damp"] ,
["Water Absorb", "Damp"] ,
["Water Absorb", "Damp"] ,
["Synchronize", "Inner Focus"] ,
["Synchronize", "Inner Focus"] ,
["Synchronize", "Inner Focus"] ,
["Guts", "No Guard"] ,
["Guts", "No Guard"] ,
["Guts", "No Guard"] ,
["Chlorophyll"] ,
["Chlorophyll"] ,
["Chlorophyll"] ,
["Clear Body", "Liquid Ooze"] ,
["Clear Body", "Liquid Ooze"] ,
["Rock Head", "Sturdy"] ,
["Rock Head", "Sturdy"] ,
["Rock Head", "Sturdy"] ,
["Run Away", "Flash Fire"] ,
["Run Away", "Flash Fire"] ,
["Oblivious", "Own Tempo"] ,
["Oblivious", "Own Tempo"] ,
["Magnet Pull", "Sturdy"] ,
["Magnet Pull", "Sturdy"] ,
["Keen Eye", "Inner Focus"] ,
["Run Away", "Early Bird"] ,
["Run Away", "Early Bird"] ,
["Thick Fat", "Hydration"] ,
["Thick Fat", "Hydration"] ,
["Stench", "Sticky Hold"] ,
["Stench", "Sticky Hold"] ,
["Shell Armor", "Skill Link"] ,
["Shell Armor", "Skill Link"] ,
["Levitate"] ,
["Levitate"] ,
["Cursed Body"] ,
["Rock Head", "Sturdy"] ,
["Insomnia", "Forewarn"] ,
["Insomnia", "Forewarn"] ,
["Hyper Cutter", "Shell Armor"] ,
["Hyper Cutter", "Shell Armor"] ,
["Soundproof", "Static"] ,
["Soundproof", "Static"] ,
["Chlorophyll"] ,
["Chlorophyll"] ,
["Rock Head", "Lightning Rod"] ,
["Rock Head", "Lightning Rod"] ,
["Limber", "Reckless"] ,
["Keen Eye", "Iron Fist"] ,
["Own Tempo", "Oblivious"] ,
["Levitate", "Neutralizing Gas"] ,
["Levitate", "Neutralizing Gas"] ,
["Lightning Rod", "Rock Head"] ,
["Lightning Rod", "Rock Head"] ,
["Natural Cure", "Serene Grace"] ,
["Chlorophyll", "Leaf Guard"] ,
["Early Bird", "Scrappy"] ,
["Swift Swim", "Sniper"] ,
["Poison Point", "Sniper"] ,
["Swift Swim", "Water Veil"] ,
["Swift Swim", "Water Veil"] ,
["Illuminate", "Natural Cure"] ,
["Illuminate", "Natural Cure"] ,
["Soundproof", "Filter"] ,
["Swarm", "Technician"] ,
["Oblivious", "Forewarn"] ,
["Static"] ,
["Flame Body"] ,
["Hyper Cutter", "Mold Breaker"] ,
["Intimidate", "Anger Point"] ,
["Swift Swim"] ,
["Intimidate"] ,
["Water Absorb", "Shell Armor"] ,
["Limber"] ,
["Run Away", "Adaptability"] ,
["Water Absorb"] ,
["Volt Absorb"] ,
["Flash Fire"] ,
["Trace", "Download"] ,
["Swift Swim", "Shell Armor"] ,
["Swift Swim", "Shell Armor"] ,
["Swift Swim", "Battle Armor"] ,
["Swift Swim", "Battle Armor"] ,
["Rock Head", "Pressure"] ,
["Immunity", "Thick Fat"] ,
["Pressure"] ,
["Pressure"] ,
["Pressure"] ,
["Shed Skin"] ,
["Shed Skin"] ,
["Inner Focus"] ,
["Pressure"] ,
["Synchronize"] ,
["Overgrow"] ,
["Overgrow"] ,
["Overgrow"] ,
["Blaze"] ,
["Blaze"] ,
["Blaze"] ,
["Torrent"] ,
["Torrent"] ,
["Torrent"] ,
["Run Away", "Keen Eye"] ,
["Run Away", "Keen Eye"] ,
["Insomnia", "Keen Eye"] ,
["Insomnia", "Keen Eye"] ,
["Swarm", "Early Bird"] ,
["Swarm", "Early Bird"] ,
["Swarm", "Insomnia"] ,
["Swarm", "Insomnia"] ,
["Inner Focus"] ,
["Volt Absorb", "Illuminate"] ,
["Volt Absorb", "Illuminate"] ,
["Static"] ,
["Cute Charm", "Magic Guard"] ,
["Cute Charm", "Competitive"] ,
["Hustle", "Serene Grace"] ,
["Hustle", "Serene Grace"] ,
["Synchronize", "Early Bird"] ,
["Synchronize", "Early Bird"] ,
["Static"] ,
["Static"] ,
["Static"] ,
["Chlorophyll"] ,
["Thick Fat", "Huge Power"] ,
["Thick Fat", "Huge Power"] ,
["Sturdy", "Rock Head"] ,
["Water Absorb", "Damp"] ,
["Chlorophyll", "Leaf Guard"] ,
["Chlorophyll", "Leaf Guard"] ,
["Chlorophyll", "Leaf Guard"] ,
["Run Away", "Pickup"] ,
["Chlorophyll", "Solar Power"] ,
["Chlorophyll", "Solar Power"] ,
["Speed Boost", "Compound Eyes"] ,
["Damp", "Water Absorb"] ,
["Damp", "Water Absorb"] ,
["Synchronize"] ,
["Synchronize"] ,
["Insomnia", "Super Luck"] ,
["Oblivious", "Own Tempo"] ,
["Levitate"] ,
["Levitate"] ,
["Shadow Tag"] ,
["Inner Focus", "Early Bird"] ,
["Sturdy"] ,
["Sturdy"] ,
["Serene Grace", "Run Away"] ,
["Hyper Cutter", "Sand Veil"] ,
["Rock Head", "Sturdy"] ,
["Intimidate", "Run Away"] ,
["Intimidate", "Quick Feet"] ,
["Poison Point", "Swift Swim"] ,
["Swarm", "Technician"] ,
["Sturdy", "Gluttony"] ,
["Swarm", "Guts"] ,
["Inner Focus", "Keen Eye"] ,
["Pickup", "Quick Feet"] ,
["Guts", "Quick Feet"] ,
["Magma Armor", "Flame Body"] ,
["Magma Armor", "Flame Body"] ,
["Oblivious", "Snow Cloak"] ,
["Oblivious", "Snow Cloak"] ,
["Hustle", "Natural Cure"] ,
["Hustle", "Sniper"] ,
["Suction Cups", "Sniper"] ,
["Vital Spirit", "Hustle"] ,
["Swift Swim", "Water Absorb"] ,
["Keen Eye", "Sturdy"] ,
["Early Bird", "Flash Fire"] ,
["Early Bird", "Flash Fire"] ,
["Swift Swim", "Sniper"] ,
["Pickup"] ,
["Sturdy"] ,
["Trace", "Download"] ,
["Intimidate", "Frisk"] ,
["Own Tempo", "Technician"] ,
["Guts", "Steadfast"] ,
["Intimidate", "Technician"] ,
["Oblivious", "Forewarn"] ,
["Static"] ,
["Flame Body"] ,
["Thick Fat", "Scrappy"] ,
["Natural Cure", "Serene Grace"] ,
["Pressure"] ,
["Pressure"] ,
["Pressure"] ,
["Guts"] ,
["Shed Skin"] ,
["Sand Stream"] ,
["Pressure"] ,
["Pressure"] ,
["Natural Cure"] ,
["Overgrow"] ,
["Overgrow"] ,
["Overgrow"] ,
["Blaze"] ,
["Blaze"] ,
["Blaze"] ,
["Torrent"] ,
["Torrent"] ,
["Torrent"] ,
["Run Away", "Quick Feet"] ,
["Intimidate", "Quick Feet"] ,
["Pickup", "Gluttony"] ,
["Pickup", "Gluttony"] ,
["Shield Dust"] ,
["Shed Skin"] ,
["Swarm"] ,
["Shed Skin"] ,
["Shield Dust"] ,
["Swift Swim", "Rain Dish"] ,
["Swift Swim", "Rain Dish"] ,
["Swift Swim", "Rain Dish"] ,
["Chlorophyll", "Early Bird"] ,
["Chlorophyll", "Early Bird"] ,
["Chlorophyll", "Early Bird"] ,
["Guts"] ,
["Guts"] ,
["Keen Eye", "Hydration"] ,
["Keen Eye", "Drizzle"] ,
["Synchronize", "Trace"] ,
["Synchronize", "Trace"] ,
["Synchronize", "Trace"] ,
["Swift Swim"] ,
["Intimidate"] ,
["Effect Spore", "Poison Heal"] ,
["Effect Spore", "Poison Heal"] ,
["Truant"] ,
["Vital Spirit"] ,
["Truant"] ,
["Compound Eyes"] ,
["Speed Boost"] ,
["Wonder Guard"] ,
["Soundproof"] ,
["Soundproof"] ,
["Soundproof"] ,
["Thick Fat", "Guts"] ,
["Thick Fat", "Guts"] ,
["Thick Fat", "Huge Power"] ,
["Sturdy", "Magnet Pull"] ,
["Cute Charm", "Normalize"] ,
["Cute Charm", "Normalize"] ,
["Keen Eye", "Stall"] ,
["Hyper Cutter", "Intimidate"] ,
["Sturdy", "Rock Head"] ,
["Sturdy", "Rock Head"] ,
["Sturdy", "Rock Head"] ,
["Pure Power"] ,
["Pure Power"] ,
["Static", "Lightning Rod"] ,
["Static", "Lightning Rod"] ,
["Plus"] ,
["Minus"] ,
["Illuminate", "Swarm"] ,
["Oblivious", "Tinted Lens"] ,
["Natural Cure", "Poison Point"] ,
["Liquid Ooze", "Sticky Hold"] ,
["Liquid Ooze", "Sticky Hold"] ,
["Rough Skin"] ,
["Rough Skin"] ,
["Water Veil", "Oblivious"] ,
["Water Veil", "Oblivious"] ,
["Oblivious", "Simple"] ,
["Magma Armor", "Solid Rock"] ,
["White Smoke", "Drought"] ,
["Thick Fat", "Own Tempo"] ,
["Thick Fat", "Own Tempo"] ,
["Own Tempo", "Tangled Feet"] ,
["Hyper Cutter", "Arena Trap"] ,
["Levitate"] ,
["Levitate"] ,
["Sand Veil"] ,
["Sand Veil"] ,
["Natural Cure"] ,
["Natural Cure"] ,
["Immunity"] ,
["Shed Skin"] ,
["Levitate"] ,
["Levitate"] ,
["Oblivious", "Anticipation"] ,
["Oblivious", "Anticipation"] ,
["Hyper Cutter", "Shell Armor"] ,
["Hyper Cutter", "Shell Armor"] ,
["Levitate"] ,
["Levitate"] ,
["Suction Cups"] ,
["Suction Cups"] ,
["Battle Armor"] ,
["Battle Armor"] ,
["Swift Swim", "Oblivious"] ,
["Marvel Scale", "Competitive"] ,
["Forecast"] ,
["Color Change"] ,
["Insomnia", "Frisk"] ,
["Insomnia", "Frisk"] ,
["Levitate"] ,
["Pressure"] ,
["Chlorophyll", "Solar Power"] ,
["Levitate"] ,
["Pressure", "Super Luck"] ,
["Shadow Tag"] ,
["Inner Focus", "Ice Body"] ,
["Inner Focus", "Ice Body"] ,
["Thick Fat", "Ice Body"] ,
["Thick Fat", "Ice Body"] ,
["Thick Fat", "Ice Body"] ,
["Shell Armor"] ,
["Swift Swim"] ,
["Swift Swim"] ,
["Swift Swim", "Rock Head"] ,
["Swift Swim"] ,
["Rock Head"] ,
["Rock Head"] ,
["Intimidate"] ,
["Clear Body"] ,
["Clear Body"] ,
["Clear Body"] ,
["Clear Body"] ,
["Clear Body"] ,
["Clear Body"] ,
["Levitate"] ,
["Levitate"] ,
["Drizzle"] ,
["Drought"] ,
["Air Lock"] ,
["Serene Grace"] ,
["Pressure"] ];
