exports.items_effects = [ '' , 'Used in battle\n:   Catches a wild Pokémon without fail.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
'Used in battle\n:   Attempts to catch a wild Pokémon, using a catch rate of 2x.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
'Used in battle\n:   Attempts to catch a wild Pokémon, using a catch rate of 1.5x.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
'ERROR' ,
'Used in battle\n:   Attempts to catch a wild Pokémon, using a catch rate of 1.5x.\n\nThis item can only be used in the great marsh or kanto safari zone.' ,
'Used in battle\n:   Attempts to catch a wild Pokémon.  If the wild Pokémon is water- or bug-type, this ball has a catch rate of 3x.  Otherwise, it has a catch rate of 1x.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
'Used in battle\n:   Attempts to catch a wild Pokémon.  If the wild Pokémon was encountered by surfing or fishing, this ball has a catch rate of 3.5x.  Otherwise, it has a catch rate of 1x.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
"Used in battle\n:   Attempts to catch a wild Pokémon.  Has a catch rate of given by `(40 - level) / 10`, where `level` is the wild Pokémon's level, to a maximum of 3.9x for level 1 Pokémon.  If the wild Pokémon's level is higher than 30, this ball has a catch rate of 1x.\n\n    If used in a trainer battle, nothing happens and the ball is lost." ,
"Used in battle\n:   Attempts to catch a wild Pokémon.  If the wild Pokémon's species is marked as caught in the trainer's Pokédex, this ball has a catch rate of 3x.  Otherwise, it has a catch rate of 1x.\n\n    If used in a trainer battle, nothing happens and the ball is lost." ,
'Used in battle\n:   Attempts to catch a wild Pokémon.  Has a catch rate of 1.1x on the first turn of the battle and increases by 0.1x every turn, to a maximum of 4x on turn 30.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
"Used in battle\n:   Attempts to catch a wild Pokémon, using a catch rate of 1x.  Whenever the caught Pokémon's happiness increases, it increases by one extra point.\n\n    If used in a trainer battle, nothing happens and the ball is lost." ,
'Used in battle\n:   Attempts to catch a wild Pokémon, using a catch rate of 1x.\n\n    If used in a trainer battle, nothing happens and the ball is lost.' ,
'Used on a friendly Pokémon\n:   Restores 20 HP.' ,
'Used on a party Pokémon\n:   Cures poison.' ,
'Used on a party Pokémon\n:   Cures a burn.' ,
'Used on a party Pokémon\n:   Cures freezing.' ,
'Used on a party Pokémon\n:   Cures sleep.' ,
'ERROR' ,
'Used on a party Pokémon\n:   Restores HP to full and cures any status ailment and confusion.' ,
'Used on a party Pokémon\n:   Restores HP to full.' ,
'Used on a party Pokémon\n:   Restores 200 HP.' ,
'Used on a party Pokémon\n:   Restores 50 HP.' ,
'Used on a party Pokémon\n:   Cures any status ailment and confusion.' ,
'Used on a party Pokémon\n:   Revives the Pokémon and restores half its HP.' ,
'Used on a party Pokémon\n:   Revives the Pokémon and restores its HP to full.' ,
'Used on a party Pokémon\n:   Restores 50 HP.' ,
'Used on a party Pokémon\n:   Restores 60 HP.' ,
'Used on a party Pokémon\n:   Restores 80 HP.' ,
'Used on a party Pokémon\n:   Restores 100 HP.' ,
'ERROR' ,
'Used on a party Pokémon\n:   Restores 200 HP.  Decreases happiness by 10/10/15.' ,
'Used on a party Pokémon\n:   Cures any status ailment.  Decreases happiness by 5/5/10.' ,
'Used on a party Pokémon\n:   Revives a fainted Pokémon and restores its HP to full.  Decreases happiness by 10/10/15.' ,
'Used on a party Pokémon\n:   Restores 10 PP for a selected move.' ,
'Used on a party Pokémon\n:   Restores PP to full for a selected move.' ,
'Used on a party Pokémon\n:   Restores 10 PP for each move.' ,
'Used on a party Pokémon\n:   Restores PP to full for each move.' ,
'Used on a party Pokémon\n:   Cures any status ailment and confusion.' ,
'Used on a party Pokémon\n:   Cures sleep.' ,
'Used on a party Pokémon in battle\n:   Cures confusion.' ,
'Used on a party Pokémon in battle\n:   Cures attraction.' ,
'Used outside of battle\n:   Decreases the wild Pokémon encounter rate by 50%.' ,
'Used outside of battle\n:   Doubles the wild Pokémon encounter rate.' ,
'Used on a party Pokémon\n:   Restores 20 HP.' ,
'Used\n:   Revives all fainted Pokémon in the party and restores their HP to full.' ,
'No effect.' ,
'No effect.' ,
'No effect.\n\nIn Diamond and Pearl, trade ten for a sunny day TM in the house midway along the southern section of sinnoh route 212.\n\nIn Platinum, trade to move tutors on sinnoh route 212, in snowpoint city, and in the survival area.  Eight shards total are required per tutelage, but the particular combination of colors varies by move.\n\nIn HeartGold and SoulSilver, trade one for a cheri berry, a leppa berry, and a pecha berry with the Juggler near the Pokémon Center in violet city.\n\nIn HeartGold and SoulSilver, trade one for a persim berry, a pomeg berry, and a razz berry with the Juggler near the pal park entrance in fuchsia city.' ,
'No effect.\n\nIn Diamond and Pearl, trade ten for a rain dance TM in the house midway along the southern section of sinnoh route 212.\n\nIn Platinum, trade to move tutors on sinnoh route 212, in snowpoint city, and in the survival area.  Eight shards total are required per tutelage, but the particular combination of colors varies by move.\n\nIn HeartGold and SoulSilver, trade one for a chesto berry, an oran berry, and a wiki berry with the Juggler near the Pokémon Center in violet city.\n\nIn HeartGold and SoulSilver, trade one for a bluk berry, a cornn berry, and a kelpsy berry with the Juggler near the pal park entrance in fuchsia city.' ,
'No effect.\n\nIn Diamond and Pearl, trade ten for a sandstorm TM in the house midway along the southern section of sinnoh route 212.\n\nIn Platinum, trade to move tutors on sinnoh route 212, in snowpoint city, and in the survival area.  Eight shards total are required per tutelage, but the particular combination of colors varies by move.\n\nIn HeartGold and SoulSilver, trade one for an aspear berry, a iapapa berry, and a sitrus berry with the Juggler near the Pokémon Center in violet city.\n\nIn HeartGold and SoulSilver, trade one for a grepa berry, a nomel berry, and a pinap berry with the Juggler near the pal park entrance in fuchsia city.' ,
'No effect.\n\nIn Diamond and Pearl, trade ten for a hail TM in the house midway along the southern section of sinnoh route 212.\n\nIn Platinum, trade to move tutors on sinnoh route 212, in snowpoint city, and in the survival area.  Eight shards total are required per tutelage, but the particular combination of colors varies by move.\n\nIn HeartGold and SoulSilver, trade one for an aguav berry, a lum berry, and a rawst berry with the Juggler near the Pokémon Center in violet city.\n\nIn HeartGold and SoulSilver, trade one for a durin berry, a hondew berry, and a wepear berry with the Juggler near the pal park entrance in fuchsia city.' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
"Used on a party Pokémon\n:   Increases HP effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases Attack effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases Defense effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases Speed effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases Special Attack effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
'Used on a party Pokémon\n:   Increases level by 1.  Increases happiness by 5/3/2.' ,
"Used on a party Pokémon\n:   Increases a selected move's max PP by 20% its original max PP, to a maximum of 1.6x.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases Special Defense effort by 10, but won't increase it beyond 100.  Increases happiness by 5/3/2." ,
"Used on a party Pokémon\n:   Increases a selected move's max PP to 1.6x its original max PP.  Increases happiness by 5/3/2." ,
'' ,
'ERROR' ,
"Used on a party Pokémon in battle\n:   Increases the target's critical hit chance by one stage until it leaves the field.  Increases happiness by 1/1/0." ,
"Used on a party Pokémon in battle\n:   Raises the target's Attack by one stage.  Increases happiness by 1/1/0." ,
'ERROR' ,
"Used on a party Pokémon in battle\n:   Raises the target's Speed by one stage.  Increases happiness by 1/1/0." ,
"Used on a party Pokémon in battle\n:   Raises the target's accuracy by one stage.  Increases happiness by 1/1/0." ,
'ERROR' ,
'ERROR' ,
'Used in battle\n:   Ends a wild battle.  Cannot be used in trainer battles.' ,
'' ,
'Used outside of battle\n:   Trainer will skip encounters with wild Pokémon of a lower level than the lead party Pokémon.  This effect wears off after the trainer takes 200 steps.' ,
'Used outside of battle\n:   Trainer will skip encounters with wild Pokémon of a lower level than the lead party Pokémon.  This effect wears off after the trainer takes 250 steps.' ,
'Used outside of battle\n:   Transports the trainer to the last-entered dungeon entrance.  Cannot be used outside, in buildings, or in distortion world, sinnoh hall of origin 1, spear pillar, or turnback cave.' ,
'Used outside of battle\n:   Trainer will skip encounters with wild Pokémon of a lower level than the lead party Pokémon.  This effect wears off after the trainer takes 100 steps.' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'Used on a party Pokémon\n:   Evolves a cottonee into whimsicott, a gloom into bellossom, a petilil into lilligant, or a sunkern into sunflora.' ,
'Used on a party Pokémon\n:   Evolves a clefairy into clefable, a jigglypuff into wigglytuff, a munna into musharna, a nidorina into nidoqueen, a nidorino into nidoking, or a skitty into delcatty.' ,
'Used on a party Pokémon\n:   Evolves an eevee into flareon, a growlithe into arcanine, a pansear into simisear, or a vulpix into ninetales.' ,
'ERROR' ,
'Used on a party Pokémon\n:   Evolves an eevee into vaporeon, a lombre into ludicolo, a panpour into simipour, a poliwhirl into poliwrath, a shellder into cloyster, or a staryu into starmie.' ,
'Used on a party Pokémon\n:   Evolves an exeggcute into exeggutor, a gloom into vileplume, a nuzleaf into shiftry, a pansage into simisage, or a weepinbell into victreebel.' ,
'' ,
'' ,
'' ,
'' ,
'ERROR' ,
'Vendor trash.' ,
'' ,
'Vendor trash.' ,
'Vendor trash.' ,
'Vendor trash.' ,
'Vendor trash.' ,
'Vendor trash.' ,
'Trade one to the Move Relearner near the shore in pastoria city or with the Move Deleter in blackthorn city to teach one party Pokémon a prior level-up move.' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
"Used to send short messages to other players via Pokémon trading.  Trainer may compose a message from a finite list of words when giving this item to a Pokémon.  Once taken and read, a message may be erased and this item can be reused, or the message may be stored in the trainer's PC.\n\nHeld\n:   Holder cannot be placed in the PC.  Any move attempting to remove this item from the holder will fail." ,
'Held in battle\n:   When the holder is paralyzed, it consumes this item to cure the paralysis.\n\nUsed on a party Pokémon\n:   Cures paralysis.' ,
'Held in battle\n:   When the holder is asleep, it consumes this item to wake up.\n\nUsed on a party Pokémon\n:   Cures sleep.' ,
'Held in battle\n:   When the holder is poisoned, it consumes this item to cure the poison.\n\nUsed on a party Pokémon\n:   Cures poison.' ,
'Held in battle\n:   When the holder is burned, it consumes this item to cure the burn.\n\nUsed on a party Pokémon\n:   Cures a burn.' ,
'Held in battle\n:   When the holder is frozen, it consumes this item to thaw itself.\n\nUsed on a party Pokémon\n:   Cures freezing.' ,
"Held in battle\n:   When the holder is out of PP for one of its moves, it consumes this item to restore 10 of that move's PP.\n\nUsed on a party Pokémon\n:   Restores 10 PP for a selected move." ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 10 HP.\n\nUsed on a party Pokémon\n:   Restores 10 HP.' ,
'Held in battle\n:   When the holder is confused, it consumes this item to cure the confusion.\n\nUsed on a party Pokémon\n:   Cures confusion.' ,
'Held in battle\n:   When the holder is afflicted with a major status ailment, it consumes this item to cure the ailment.\n\nUsed on a party Pokémon\n:   Cures any major status ailment.' ,
"Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/4 its max HP.\n\nUsed on a party Pokémon\n:   Restores 1/4 the Pokémon's max HP." ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/8 its max HP.  If the holder dislikes spicy flavors (i.e., has a nature that lowers Attack), it will also become confused.' ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/8 its max HP.  If the holder dislikes dry flavors (i.e., has a nature that lowers Special Attack), it will also become confused.' ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/8 its max HP.  If the holder dislikes sweet flavors (i.e., has a nature that lowers Speed), it will also become confused.' ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/8 its max HP.  If the holder dislikes bitter flavors (i.e., has a nature that lowers Special Defense), it will also become confused.' ,
'Held in battle\n:   When the holder has 1/2 its max HP remaining or less, it consumes this item to restore 1/8 its max HP.  If the holder dislikes sour flavors (i.e., has a nature that lowers Defense), it will also become confused.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers HP effort by 10.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers Attack effort by 10.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers Defense effort by 10.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers Special Attack effort by 10.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers Special Defense effort by 10.' ,
'Used on a party Pokémon\n:   Increases happiness by 10/5/2.  Lowers Speed effort by 10.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'No effect; only useful for planting and cooking.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its Attack by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its Defense by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its Speed by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its Special Attack by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its Special Defense by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise its critical hit chance by one stage.' ,
'Held in battle\n:   When the holder has 1/4 its max HP remaining or less, it consumes this item to raise a random stat by two stages.' ,
'Held in battle\n:   When the holder takes super-effective damage, it consumes this item to restore 1/4 its max HP.' ,
'' ,
'' ,
'' ,
'ERROR' ,
"Held in battle\n:   At the end of each turn, if any of the holder's stats have a negative stat modifier, the holder consumes this item to remove the modifiers from those stats." ,
'Held\n:   When the holder would gain effort due to battle, it gains double that effort instead.\n\nHeld in battle\n:   Holder has half its Speed.' ,
'ERROR' ,
'Held in battle\n:   Whenever the holder attempts to use a move, it has a 3/16 chance to act first among moves with the same priority.  If multiple Pokémon have this effect at the same time, Speed is the tie-breaker as normal, but the effect of trick room is ignored.' ,
'Held\n:   When the holder would earn happiness for any reason, it earns twice that amount instead.' ,
'Held in battle\n:   When the holder is attracted, it consumes this item to cure the attraction.' ,
'Held in battle\n:   Holder has 1.5x its Attack.  When the holder attempts to use a move, all its other moves are disabled until it leaves battle or loses this item.\n\n    The restriction ends even if this item is swapped for another Choice item\nvia trick or switcheroo.' ,
'ERROR' ,
'ERROR' ,
'Held\n:   If the holder participated in a trainer battle, the trainer earns twice the usual prize money.  This effect applies even if the holder fainted.\n\n    This effect does not stack with any other similar effect.' ,
'Held by lead Pokémon: Prevents wild battles with Pokémon that are lower level than the holder.' ,
"Held by Latias or Latios: Increases the holder's Special Attack and Special Defense by 50%." ,
'ERROR' ,
'ERROR' ,
"Held: In wild battles, attempts to run away on the holder's turn will always succeed." ,
'Held: Prevents the holder from evolving naturally.  Evolution initiated by the trainer (Stones, etc) will still work.' ,
"Held: If the holder is attacked for regular damage that would faint it, this item has a 10% chance to prevent the holder's HP from lowering below 1." ,
'Held: Increases any Exp the holder gains by 50%.' ,
"Held: Raises the holder's critical hit counter by 1." ,
"Held: Increases the power of the holder's Steel moves by 20%.\nHeld by Onix or Scyther: Evolves the holder into Steelix or Scizor when traded, respectively." ,
'Held: Heals the holder by 1/16 its max HP at the end of each turn.' ,
'Held by Seadra: Evolves the holder into Kingdra when traded.' ,
"Held by Pikachu: Doubles the holder's initial Attack and Special Attack." ,
"Held: Increases the power of the holder's Ground moves by 20%." ,
"Held: Increases the power of the holder's Rock moves by 20%." ,
"Held: Increases the power of the holder's Grass moves by 20%." ,
'ERROR' ,
"Held: Increases the power of the holder's Fighting moves by 20%." ,
"Held: Increases the power of the holder's Electric moves by 20%." ,
"Held: Increases the power of the holder's Water moves by 20%." ,
"Held: Increases the power of the holder's Flying moves by 20%." ,
"Held: Increases the power of the holder's Poison moves by 20%." ,
'ERROR' ,
"Held: Increases the power of the holder's Ghost moves by 20%." ,
'ERROR' ,
"Held: Increases the power of the holder's Fire moves by 20%." ,
"Held: Increases the power of the holder's Dragon moves by 20%." ,
"Held: Increases the power of the holder's Normal moves by 20%." ,
'Held by Porygon: Evolves the holder into Porygon2 when traded.' ,
'Held: Heals the holder by 1/8 of any damage it inflicts.' ,
"Held: Increases the power of the holder's Water moves by 20%." ,
"Held: Increases the holder's Evasion by 5%." ,
"Held by Chansey: Raises the holder's critical hit counter by 2." ,
"Held by Ditto: Increases the holder's initial Defense and Special Defense by 50%." ,
"Held by Cubone or Marowak: Doubles the holder's Attack." ,
"Held by Farfetch'd: Raises the holder's critical hit counter by 2." ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
'' ,
"Held: Increases the holder's Coolness during a Super Contest's Visual Competition." ,
"Held: Increases the holder's Beauty during a Super Contest's Visual Competition." ,
"Held: Increases the holder's Cuteness during a Super Contest's Visual Competition." ,
"Held: Increases the holder's Smartness during a Super Contest's Visual Competition." ,
"Held: Increases the holder's Toughness during a Super Contest's Visual Competition." ,
'Increases movement speed outside or in caves.  Faster than the acro bike.  Allows the trainer to ascend muddy slopes.' ,
'Contains the Coins used by the Game Corner, to a maximum of 50,000.' ,
'ERROR' ,
'Used to find Pokémon on the Old Rod list for an area, which are generally Magikarp or similar.' ,
'Used to find Pokémon on the Good Rod list for an area, which are generally mediocre.' ,
'Used to find Pokémon on the Super Rod list for an area, which are generally the best available there.' ,
'ERROR' ,
'Allows the trainer to enter Contests.' ,
'' ,
'Waters Berry plants.' ,
'Contains a machine part to be delivered to Captain Stern.' ,
'Collects soot when walking through tall grass on hoenn route 113.' ,
'Used by trainer outside of battle\n:   Opens the door to the basement tunnel under goldenrod city.' ,
'Increases movement speed outside or in caves.  Slower than the mach bike.  Can perform various tricks, allowing the trainer to reach certain special areas.' ,
'ERROR' ,
'Contains a letter to be delivered to Steven.' ,
'Provides access to southern island and either latias or latios, whichever is not available roaming around Hoenn.' ,
'Causes groudon to appear in the embedded tower.' ,
'Causes kyogre to appear in the embedded tower.' ,
'May be traded to Captain Stern for a deep sea tooth or a deep sea scale.' ,
'Allows the trainer to enter the desert on hoenn route 111.' ,
"RSE: May be traded to Professor Cozmo for tm27.\n\nFRLG: A meteorite to be delivered to Lostelle's father." ,
'ERROR' ,
'ERROR' ,
'ERROR' ,
'ERROR' ,
'Grants access to the Team Galactic warehouse in Veilstone City.' ,
'Give to a scientist in the mining museum in oreburgh city or the Museum of Science in pewter city to receive a lileep.' ,
'Give to a scientist in the mining museum in oreburgh city or the Museum of Science in pewter city to receive a anorith.' ,
'Reveals invisble kecleon on the overworld.' ,
'Teaches Focus Punch to a compatible Pokémon.' ,
'Teaches Dragon Claw to a compatible Pokémon.' ,
'Teaches Water Pulse to a compatible Pokémon.' ,
'Teaches Calm Mind to a compatible Pokémon.' ,
'Teaches Roar to a compatible Pokémon.' ,
'Teaches Toxic to a compatible Pokémon.' ,
'Teaches Hail to a compatible Pokémon.' ,
'Teaches Bulk Up to a compatible Pokémon.' ,
'Teaches Bullet Seed to a compatible Pokémon.' ,
'Teaches Hidden Power to a compatible Pokémon.' ,
'Teaches Sunny Day to a compatible Pokémon.' ,
'Teaches Taunt to a compatible Pokémon.' ,
'Teaches Ice Beam to a compatible Pokémon.' ,
'Teaches Blizzard to a compatible Pokémon.' ,
'Teaches Hyper Beam to a compatible Pokémon.' ,
'Teaches Light Screen to a compatible Pokémon.' ,
'Teaches Protect to a compatible Pokémon.' ,
'Teaches Rain Dance to a compatible Pokémon.' ,
'Teaches Giga Drain to a compatible Pokémon.' ,
'Teaches Safeguard to a compatible Pokémon.' ,
'Teaches Frustration to a compatible Pokémon.' ,
'Teaches SolarBeam to a compatible Pokémon.' ,
'Teaches Iron Tail to a compatible Pokémon.' ,
'Teaches Thunderbolt to a compatible Pokémon.' ,
'Teaches Thunder to a compatible Pokémon.' ,
'Teaches Earthquake to a compatible Pokémon.' ,
'Teaches Return to a compatible Pokémon.' ,
'Teaches Dig to a compatible Pokémon.' ,
'Teaches Psychic to a compatible Pokémon.' ,
'Teaches Shadow Ball to a compatible Pokémon.' ,
'Teaches Brick Break to a compatible Pokémon.' ,
'Teaches Double Team to a compatible Pokémon.' ,
'Teaches Reflect to a compatible Pokémon.' ,
'Teaches Shock Wave to a compatible Pokémon.' ,
'Teaches Flamethrower to a compatible Pokémon.' ,
'Teaches Sludge Bomb to a compatible Pokémon.' ,
'Teaches Sandstorm to a compatible Pokémon.' ,
'Teaches Fire Blast to a compatible Pokémon.' ,
'Teaches Rock Tomb to a compatible Pokémon.' ,
'Teaches Aerial Ace to a compatible Pokémon.' ,
'Teaches Torment to a compatible Pokémon.' ,
'Teaches Facade to a compatible Pokémon.' ,
'Teaches Secret Power to a compatible Pokémon.' ,
'Teaches Rest to a compatible Pokémon.' ,
'Teaches Attract to a compatible Pokémon.' ,
'Teaches Thief to a compatible Pokémon.' ,
'Teaches Steel Wing to a compatible Pokémon.' ,
'Teaches Skill Swap to a compatible Pokémon.' ,
'Teaches Snatch to a compatible Pokémon.' ,
'Teaches Overheat to a compatible Pokémon.' ,
'Teaches Cut to a compatible Pokémon.' ,
'Teaches Fly to a compatible Pokémon.' ,
'Teaches Surf to a compatible Pokémon.' ,
'Teaches Strength to a compatible Pokémon.' ,
'Teaches Defog to a compatible Pokémon.' ,
'Teaches Rock Smash to a compatible Pokémon.' ,
'Teaches Waterfall to a compatible Pokémon.' ,
'Teaches Rock Climb to a compatible Pokémon.' ,
'' ,
'' ,
'ERROR' ,
'ERROR' ,
"Used by trainer in the Galactic Eterna Building, on the ground floor, to the left of the TV\n:   Unlocks the secret rotom room, in which there are five appliances which can change Rotom's form." ,
'May be traded for a bicycle.' ,
"The Safari Zone warden's teeth, to be returned to him for hm04." ,
'Give to a scientist in the mining museum in oreburgh city or the Museum of Science in pewter city to receive a aerodactyl.' ,
'Used by trainer outside of battle\n:   Opens doors in the goldenrod city Radio Tower.' ,
'Operates the elevator in the Celadon Rocket Hideout.' ,
'Give to a scientist in the mining museum in oreburgh city or the Museum of Science in pewter city to receive a omanyte.' ,
'Give to a scientist in the mining museum in oreburgh city or the Museum of Science in pewter city to receive a kabuto.' ,
'Identifies ghosts in pokemon tower.' ,
'Increases movement speed outside or in caves.  In high gear, allows the trainer to hop over some rocks and ascend muddy slopes.' ,
"Displays a map of the region including the trainer's position, location names, visited towns, gym locations, and where the trainer has been walking recently." ,
'Reveals trainers who want a rematch, by showing !! over their heads.  Each use drains the battery; requires 100 steps to charge.' ,
'Records information on various famous people.' ,
'Stores TMs and HMs.' ,
'Stores Berries.' ,
'Teaches beginning trainers basic information.' ,
'Provides access to the first three Sevii Islands.' ,
'Provides access to the Sevii Islands.' ,
'Used to bribe the saffron city guards for entry to the city.' ,
'Provides access to Navel Rock, ho oh, and lugia.' ,
'Provides access to Birth Island and deoxys.' ,
'Holds Berry Powder from Berry Crushing.' ,
'Deliver to Celio for use in the Network Machine.' ,
'Deliver to Celio for use in the Network Machine.' ,
'Provides access to the magma hideout in the jagged pass.' ,
'Provides access to Faraway Island and mew.' ]
