exports.moves = [ {} , {"name": "Pound", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 35, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Karate Chop", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 25, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Double Slap", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 10, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Comet Punch", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 18, "accuracy": 18, "gen": 1} ,
{"name": "Mega Punch", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Pay Day", "type": "Normal", "category": "Physical", "contest": "Clever", "pp": 20, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Fire Punch", "type": "Fire", "category": "Physical", "contest": "Tough", "pp": 15, "power": 75, "accuracy": 75, "gen": 1} ,
{"name": "Ice Punch", "type": "Ice", "category": "Physical", "contest": "Beautiful", "pp": 15, "power": 75, "accuracy": 75, "gen": 1} ,
{"name": "Thunder Punch", "type": "Electric", "category": "Physical", "contest": "Cool", "pp": 15, "power": 75, "accuracy": 75, "gen": 1} ,
{"name": "Scratch", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 35, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Vise Grip", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 30, "power": 55, "accuracy": 55, "gen": 1} ,
{"name": "Guillotine", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 5, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Razor Wind", "type": "Normal", "category": "Special", "contest": "Cool", "pp": 10, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Swords Dance", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Cut", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 30, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Gust", "type": "Flying", "category": "Special", "contest": "Clever", "pp": 35, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Wing Attack", "type": "Flying", "category": "Physical", "contest": "Cool", "pp": 35, "power": 60, "accuracy": 60, "gen": 1} ,
{"name": "Whirlwind", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Fly", "type": "Flying", "category": "Physical", "contest": "Clever", "pp": 15, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Bind", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Slam", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Vine Whip", "type": "Grass", "category": "Physical", "contest": "Cool", "pp": 25, "power": 45, "accuracy": 45, "gen": 1} ,
{"name": "Stomp", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Double Kick", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 30, "power": 30, "accuracy": 30, "gen": 1} ,
{"name": "Mega Kick", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 5, "power": 120, "accuracy": 120, "gen": 1} ,
{"name": "Jump Kick", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 10, "power": 100, "accuracy": 100, "gen": 1} ,
{"name": "Rolling Kick", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 15, "power": 60, "accuracy": 60, "gen": 1} ,
{"name": "Sand Attack", "type": "Ground", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Headbutt", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 70, "accuracy": 70, "gen": 1} ,
{"name": "Horn Attack", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 25, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Fury Attack", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 20, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Horn Drill", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 5, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Tackle", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 35, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Body Slam", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 85, "accuracy": 85, "gen": 1} ,
{"name": "Wrap", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Take Down", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Thrash", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 10, "power": 120, "accuracy": 120, "gen": 1} ,
{"name": "Double-Edge", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 120, "accuracy": 120, "gen": 1} ,
{"name": "Tail Whip", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Poison Sting", "type": "Poison", "category": "Physical", "contest": "Clever", "pp": 35, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Twineedle", "type": "Bug", "category": "Physical", "contest": "Cool", "pp": 20, "power": 25, "accuracy": 25, "gen": 1} ,
{"name": "Pin Missile", "type": "Bug", "category": "Physical", "contest": "Cool", "pp": 20, "power": 25, "accuracy": 25, "gen": 1} ,
{"name": "Leer", "type": "Normal", "category": "Status", "contest": "Cool", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Bite", "type": "Dark", "category": "Physical", "contest": "Tough", "pp": 25, "power": 60, "accuracy": 60, "gen": 1} ,
{"name": "Growl", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Roar", "type": "Normal", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Sing", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Supersonic", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Sonic Boom", "type": "Normal", "category": "Special", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Disable", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Acid", "type": "Poison", "category": "Special", "contest": "Clever", "pp": 30, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Ember", "type": "Fire", "category": "Special", "contest": "Cute", "pp": 25, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Flamethrower", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Mist", "type": "Ice", "category": "Status", "contest": "Beautiful", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Water Gun", "type": "Water", "category": "Special", "contest": "Cute", "pp": 25, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Hydro Pump", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 110, "accuracy": 110, "gen": 1} ,
{"name": "Surf", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Ice Beam", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 10, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Blizzard", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 110, "accuracy": 110, "gen": 1} ,
{"name": "Psybeam", "type": "Psychic", "category": "Special", "contest": "Beautiful", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Bubble Beam", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Aurora Beam", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Hyper Beam", "type": "Normal", "category": "Special", "contest": "Cool", "pp": 5, "power": 150, "accuracy": 150, "gen": 1} ,
{"name": "Peck", "type": "Flying", "category": "Physical", "contest": "Cool", "pp": 35, "power": 35, "accuracy": 35, "gen": 1} ,
{"name": "Drill Peck", "type": "Flying", "category": "Physical", "contest": "Cool", "pp": 20, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Submission", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 20, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Low Kick", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Counter", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Seismic Toss", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Strength", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Absorb", "type": "Grass", "category": "Special", "contest": "Clever", "pp": 25, "power": 20, "accuracy": 20, "gen": 1} ,
{"name": "Mega Drain", "type": "Grass", "category": "Special", "contest": "Clever", "pp": 15, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Leech Seed", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Growth", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Razor Leaf", "type": "Grass", "category": "Physical", "contest": "Cool", "pp": 25, "power": 55, "accuracy": 55, "gen": 1} ,
{"name": "Solar Beam", "type": "Grass", "category": "Special", "contest": "Cool", "pp": 10, "power": 120, "accuracy": 120, "gen": 1} ,
{"name": "Poison Powder", "type": "Poison", "category": "Status", "contest": "Clever", "pp": 35, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Stun Spore", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Sleep Powder", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Petal Dance", "type": "Grass", "category": "Special", "contest": "Beautiful", "pp": 10, "power": 120, "accuracy": 120, "gen": 1} ,
{"name": "String Shot", "type": "Bug", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Dragon Rage", "type": "Dragon", "category": "Special", "contest": "Cool", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Fire Spin", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 35, "accuracy": 35, "gen": 1} ,
{"name": "Thunder Shock", "type": "Electric", "category": "Special", "contest": "Cool", "pp": 30, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Thunderbolt", "type": "Electric", "category": "Special", "contest": "Cool", "pp": 15, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Thunder Wave", "type": "Electric", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Thunder", "type": "Electric", "category": "Special", "contest": "Cool", "pp": 10, "power": 110, "accuracy": 110, "gen": 1} ,
{"name": "Rock Throw", "type": "Rock", "category": "Physical", "contest": "Tough", "pp": 15, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Earthquake", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 10, "power": 100, "accuracy": 100, "gen": 1} ,
{"name": "Fissure", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 5, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Dig", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 10, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Toxic", "type": "Poison", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Confusion", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 25, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Psychic", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 10, "power": 90, "accuracy": 90, "gen": 1} ,
{"name": "Hypnosis", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Meditate", "type": "Psychic", "category": "Status", "contest": "Beautiful", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Agility", "type": "Psychic", "category": "Status", "contest": "Cool", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Quick Attack", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 30, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Rage", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 20, "power": 20, "accuracy": 20, "gen": 1} ,
{"name": "Teleport", "type": "Psychic", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Night Shade", "type": "Ghost", "category": "Special", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Mimic", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Screech", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Double Team", "type": "Normal", "category": "Status", "contest": "Cool", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Recover", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Harden", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Minimize", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Smokescreen", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Confuse Ray", "type": "Ghost", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Withdraw", "type": "Water", "category": "Status", "contest": "Cute", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Defense Curl", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Barrier", "type": "Psychic", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Light Screen", "type": "Psychic", "category": "Status", "contest": "Beautiful", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Haze", "type": "Ice", "category": "Status", "contest": "Beautiful", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Reflect", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Focus Energy", "type": "Normal", "category": "Status", "contest": "Cool", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Bide", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Metronome", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Mirror Move", "type": "Flying", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Self-Destruct", "type": "Normal", "category": "Physical", "contest": "Beautiful", "pp": 5, "power": 200, "accuracy": 200, "gen": 1} ,
{"name": "Egg Bomb", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 10, "power": 100, "accuracy": 100, "gen": 1} ,
{"name": "Lick", "type": "Ghost", "category": "Physical", "contest": "Cute", "pp": 30, "power": 30, "accuracy": 30, "gen": 1} ,
{"name": "Smog", "type": "Poison", "category": "Special", "contest": "Tough", "pp": 20, "power": 30, "accuracy": 30, "gen": 1} ,
{"name": "Sludge", "type": "Poison", "category": "Special", "contest": "Tough", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Bone Club", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 20, "power": 65, "accuracy": 65, "gen": 1} ,
{"name": "Fire Blast", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 110, "accuracy": 110, "gen": 1} ,
{"name": "Waterfall", "type": "Water", "category": "Physical", "contest": "Tough", "pp": 15, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Clamp", "type": "Water", "category": "Physical", "contest": "Tough", "pp": 15, "power": 35, "accuracy": 35, "gen": 1} ,
{"name": "Swift", "type": "Normal", "category": "Special", "contest": "Cool", "pp": 20, "power": 60, "accuracy": 60, "gen": 1} ,
{"name": "Skull Bash", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 10, "power": 130, "accuracy": 130, "gen": 1} ,
{"name": "Spike Cannon", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 15, "power": 20, "accuracy": 20, "gen": 1} ,
{"name": "Constrict", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 35, "power": 10, "accuracy": 10, "gen": 1} ,
{"name": "Amnesia", "type": "Psychic", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Kinesis", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Soft-Boiled", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "High Jump Kick", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 10, "power": 130, "accuracy": 130, "gen": 1} ,
{"name": "Glare", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Dream Eater", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 15, "power": 100, "accuracy": 100, "gen": 1} ,
{"name": "Poison Gas", "type": "Poison", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Barrage", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 20, "power": 15, "accuracy": 15, "gen": 1} ,
{"name": "Leech Life", "type": "Bug", "category": "Physical", "contest": "Clever", "pp": 10, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Lovely Kiss", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Sky Attack", "type": "Flying", "category": "Physical", "contest": "Cool", "pp": 5, "power": 140, "accuracy": 140, "gen": 1} ,
{"name": "Transform", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Bubble", "type": "Water", "category": "Special", "contest": "Cute", "pp": 30, "power": 40, "accuracy": 40, "gen": 1} ,
{"name": "Dizzy Punch", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 10, "power": 70, "accuracy": 70, "gen": 1} ,
{"name": "Spore", "type": "Grass", "category": "Status", "contest": "Beautiful", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Flash", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Psywave", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Splash", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 40, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Acid Armor", "type": "Poison", "category": "Status", "contest": "Tough", "pp": 20, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Crabhammer", "type": "Water", "category": "Physical", "contest": "Tough", "pp": 10, "power": 100, "accuracy": 100, "gen": 1} ,
{"name": "Explosion", "type": "Normal", "category": "Physical", "contest": "Beautiful", "pp": 5, "power": 250, "accuracy": 250, "gen": 1} ,
{"name": "Fury Swipes", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 15, "power": 18, "accuracy": 18, "gen": 1} ,
{"name": "Bonemerang", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 10, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Rest", "type": "Psychic", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Rock Slide", "type": "Rock", "category": "Physical", "contest": "Tough", "pp": 10, "power": 75, "accuracy": 75, "gen": 1} ,
{"name": "Hyper Fang", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 15, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Sharpen", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Conversion", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 30, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Tri Attack", "type": "Normal", "category": "Special", "contest": "Beautiful", "pp": 10, "power": 80, "accuracy": 80, "gen": 1} ,
{"name": "Super Fang", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Slash", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 20, "power": 70, "accuracy": 70, "gen": 1} ,
{"name": "Substitute", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 1} ,
{"name": "Struggle", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 1, "power": 50, "accuracy": 50, "gen": 1} ,
{"name": "Sketch", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 1, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Triple Kick", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 10, "power": 10, "accuracy": 10, "gen": 2} ,
{"name": "Thief", "type": "Dark", "category": "Physical", "contest": "Tough", "pp": 25, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Spider Web", "type": "Bug", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Mind Reader", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Nightmare", "type": "Ghost", "category": "Status", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Flame Wheel", "type": "Fire", "category": "Physical", "contest": "Beautiful", "pp": 25, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Snore", "type": "Normal", "category": "Special", "contest": "Cute", "pp": 15, "power": 50, "accuracy": 50, "gen": 2} ,
{"name": "Curse", "type": "Ghost", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Flail", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Conversion 2", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 30, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Aeroblast", "type": "Flying", "category": "Special", "contest": "Cool", "pp": 5, "power": 100, "accuracy": 100, "gen": 2} ,
{"name": "Cotton Spore", "type": "Grass", "category": "Status", "contest": "Beautiful", "pp": 40, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Reversal", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Spite", "type": "Ghost", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Powder Snow", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 25, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Protect", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Mach Punch", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 30, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Scary Face", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Feint Attack", "type": "Dark", "category": "Physical", "contest": "Clever", "pp": 20, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Sweet Kiss", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Belly Drum", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Sludge Bomb", "type": "Poison", "category": "Special", "contest": "Tough", "pp": 10, "power": 90, "accuracy": 90, "gen": 2} ,
{"name": "Mud-Slap", "type": "Ground", "category": "Special", "contest": "Cute", "pp": 10, "power": 20, "accuracy": 20, "gen": 2} ,
{"name": "Octazooka", "type": "Water", "category": "Special", "contest": "Tough", "pp": 10, "power": 65, "accuracy": 65, "gen": 2} ,
{"name": "Spikes", "type": "Ground", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Zap Cannon", "type": "Electric", "category": "Special", "contest": "Cool", "pp": 5, "power": 120, "accuracy": 120, "gen": 2} ,
{"name": "Foresight", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Destiny Bond", "type": "Ghost", "category": "Status", "contest": "Clever", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Perish Song", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Icy Wind", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 55, "accuracy": 55, "gen": 2} ,
{"name": "Detect", "type": "Fighting", "category": "Status", "contest": "Cool", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Bone Rush", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 10, "power": 25, "accuracy": 25, "gen": 2} ,
{"name": "Lock-On", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Outrage", "type": "Dragon", "category": "Physical", "contest": "Cool", "pp": 10, "power": 120, "accuracy": 120, "gen": 2} ,
{"name": "Sandstorm", "type": "Rock", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Giga Drain", "type": "Grass", "category": "Special", "contest": "Clever", "pp": 5, "power": 75, "accuracy": 75, "gen": 2} ,
{"name": "Endure", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Charm", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Rollout", "type": "Rock", "category": "Physical", "contest": "Cute", "pp": 20, "power": 30, "accuracy": 30, "gen": 2} ,
{"name": "False Swipe", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 40, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Swagger", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Milk Drink", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Spark", "type": "Electric", "category": "Physical", "contest": "Cool", "pp": 20, "power": 65, "accuracy": 65, "gen": 2} ,
{"name": "Fury Cutter", "type": "Bug", "category": "Physical", "contest": "Cool", "pp": 20, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Steel Wing", "type": "Steel", "category": "Physical", "contest": "Cool", "pp": 25, "power": 70, "accuracy": 70, "gen": 2} ,
{"name": "Mean Look", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Attract", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Sleep Talk", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Heal Bell", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Return", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Present", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Frustration", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Safeguard", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 25, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Pain Split", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Sacred Fire", "type": "Fire", "category": "Physical", "contest": "Beautiful", "pp": 5, "power": 100, "accuracy": 100, "gen": 2} ,
{"name": "Magnitude", "type": "Ground", "category": "Physical", "contest": "Tough", "pp": 30, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Dynamic Punch", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 5, "power": 100, "accuracy": 100, "gen": 2} ,
{"name": "Megahorn", "type": "Bug", "category": "Physical", "contest": "Cool", "pp": 10, "power": 120, "accuracy": 120, "gen": 2} ,
{"name": "Dragon Breath", "type": "Dragon", "category": "Special", "contest": "Cool", "pp": 20, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Baton Pass", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 40, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Encore", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Pursuit", "type": "Dark", "category": "Physical", "contest": "Clever", "pp": 20, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Rapid Spin", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 40, "power": 50, "accuracy": 50, "gen": 2} ,
{"name": "Sweet Scent", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Iron Tail", "type": "Steel", "category": "Physical", "contest": "Cool", "pp": 15, "power": 100, "accuracy": 100, "gen": 2} ,
{"name": "Metal Claw", "type": "Steel", "category": "Physical", "contest": "Cool", "pp": 35, "power": 50, "accuracy": 50, "gen": 2} ,
{"name": "Vital Throw", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 10, "power": 70, "accuracy": 70, "gen": 2} ,
{"name": "Morning Sun", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Synthesis", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Moonlight", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Hidden Power", "type": "Normal", "category": "Special", "contest": "Clever", "pp": 15, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Cross Chop", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 5, "power": 100, "accuracy": 100, "gen": 2} ,
{"name": "Twister", "type": "Dragon", "category": "Special", "contest": "Cool", "pp": 20, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Rain Dance", "type": "Water", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Sunny Day", "type": "Fire", "category": "Status", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Crunch", "type": "Dark", "category": "Physical", "contest": "Tough", "pp": 15, "power": 80, "accuracy": 80, "gen": 2} ,
{"name": "Mirror Coat", "type": "Psychic", "category": "Special", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Psych Up", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Extreme Speed", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 5, "power": 80, "accuracy": 80, "gen": 2} ,
{"name": "Ancient Power", "type": "Rock", "category": "Special", "contest": "Tough", "pp": 5, "power": 60, "accuracy": 60, "gen": 2} ,
{"name": "Shadow Ball", "type": "Ghost", "category": "Special", "contest": "Clever", "pp": 15, "power": 80, "accuracy": 80, "gen": 2} ,
{"name": "Future Sight", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 10, "power": 120, "accuracy": 120, "gen": 2} ,
{"name": "Rock Smash", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 15, "power": 40, "accuracy": 40, "gen": 2} ,
{"name": "Whirlpool", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 35, "accuracy": 35, "gen": 2} ,
{"name": "Beat Up", "type": "Dark", "category": "Physical", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 2} ,
{"name": "Fake Out", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 10, "power": 40, "accuracy": 40, "gen": 3} ,
{"name": "Uproar", "type": "Normal", "category": "Special", "contest": "Cute", "pp": 10, "power": 90, "accuracy": 90, "gen": 3} ,
{"name": "Stockpile", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Spit Up", "type": "Normal", "category": "Special", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Swallow", "type": "Normal", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Heat Wave", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 10, "power": 95, "accuracy": 95, "gen": 3} ,
{"name": "Hail", "type": "Ice", "category": "Status", "contest": "Beautiful", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Torment", "type": "Dark", "category": "Status", "contest": "Tough", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Flatter", "type": "Dark", "category": "Status", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Will-O-Wisp", "type": "Fire", "category": "Status", "contest": "Beautiful", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Memento", "type": "Dark", "category": "Status", "contest": "Tough", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Facade", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 20, "power": 70, "accuracy": 70, "gen": 3} ,
{"name": "Focus Punch", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 20, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Smelling Salts", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 10, "power": 70, "accuracy": 70, "gen": 3} ,
{"name": "Follow Me", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Nature Power", "type": "Normal", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Charge", "type": "Electric", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Taunt", "type": "Dark", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Helping Hand", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Trick", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Role Play", "type": "Psychic", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Wish", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Assist", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Ingrain", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Superpower", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 5, "power": 120, "accuracy": 120, "gen": 3} ,
{"name": "Magic Coat", "type": "Psychic", "category": "Status", "contest": "Beautiful", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Recycle", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Revenge", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 10, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Brick Break", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 15, "power": 75, "accuracy": 75, "gen": 3} ,
{"name": "Yawn", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Knock Off", "type": "Dark", "category": "Physical", "contest": "Clever", "pp": 20, "power": 65, "accuracy": 65, "gen": 3} ,
{"name": "Endeavor", "type": "Normal", "category": "Physical", "contest": "Tough", "pp": 5, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Eruption", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Skill Swap", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Imprison", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Refresh", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Grudge", "type": "Ghost", "category": "Status", "contest": "Tough", "pp": 5, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Snatch", "type": "Dark", "category": "Status", "contest": "Clever", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Secret Power", "type": "Normal", "category": "Physical", "contest": "Clever", "pp": 20, "power": 70, "accuracy": 70, "gen": 3} ,
{"name": "Dive", "type": "Water", "category": "Physical", "contest": "Beautiful", "pp": 10, "power": 80, "accuracy": 80, "gen": 3} ,
{"name": "Arm Thrust", "type": "Fighting", "category": "Physical", "contest": "Tough", "pp": 20, "power": 15, "accuracy": 15, "gen": 3} ,
{"name": "Camouflage", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Tail Glow", "type": "Bug", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Luster Purge", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 5, "power": 70, "accuracy": 70, "gen": 3} ,
{"name": "Mist Ball", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 5, "power": 70, "accuracy": 70, "gen": 3} ,
{"name": "Feather Dance", "type": "Flying", "category": "Status", "contest": "Beautiful", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Teeter Dance", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Blaze Kick", "type": "Fire", "category": "Physical", "contest": "Cool", "pp": 10, "power": 85, "accuracy": 85, "gen": 3} ,
{"name": "Mud Sport", "type": "Ground", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Ice Ball", "type": "Ice", "category": "Physical", "contest": "Beautiful", "pp": 20, "power": 30, "accuracy": 30, "gen": 3} ,
{"name": "Needle Arm", "type": "Grass", "category": "Physical", "contest": "Clever", "pp": 15, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Slack Off", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 10, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Hyper Voice", "type": "Normal", "category": "Special", "contest": "Cool", "pp": 10, "power": 90, "accuracy": 90, "gen": 3} ,
{"name": "Poison Fang", "type": "Poison", "category": "Physical", "contest": "Clever", "pp": 15, "power": 50, "accuracy": 50, "gen": 3} ,
{"name": "Crush Claw", "type": "Normal", "category": "Physical", "contest": "Cool", "pp": 10, "power": 75, "accuracy": 75, "gen": 3} ,
{"name": "Blast Burn", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Hydro Cannon", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Meteor Mash", "type": "Steel", "category": "Physical", "contest": "Cool", "pp": 10, "power": 90, "accuracy": 90, "gen": 3} ,
{"name": "Astonish", "type": "Ghost", "category": "Physical", "contest": "Cute", "pp": 15, "power": 30, "accuracy": 30, "gen": 3} ,
{"name": "Weather Ball", "type": "Normal", "category": "Special", "contest": "Beautiful", "pp": 10, "power": 50, "accuracy": 50, "gen": 3} ,
{"name": "Aromatherapy", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 5, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Fake Tears", "type": "Dark", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Air Cutter", "type": "Flying", "category": "Special", "contest": "Cool", "pp": 25, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Overheat", "type": "Fire", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 130, "accuracy": 130, "gen": 3} ,
{"name": "Odor Sleuth", "type": "Normal", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Rock Tomb", "type": "Rock", "category": "Physical", "contest": "Clever", "pp": 15, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Silver Wind", "type": "Bug", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Metal Sound", "type": "Steel", "category": "Status", "contest": "Clever", "pp": 40, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Grass Whistle", "type": "Grass", "category": "Status", "contest": "Clever", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Tickle", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Cosmic Power", "type": "Psychic", "category": "Status", "contest": "Beautiful", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Water Spout", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Signal Beam", "type": "Bug", "category": "Special", "contest": "Beautiful", "pp": 15, "power": 75, "accuracy": 75, "gen": 3} ,
{"name": "Shadow Punch", "type": "Ghost", "category": "Physical", "contest": "Clever", "pp": 20, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Extrasensory", "type": "Psychic", "category": "Special", "contest": "Cool", "pp": 20, "power": 80, "accuracy": 80, "gen": 3} ,
{"name": "Sky Uppercut", "type": "Fighting", "category": "Physical", "contest": "Cool", "pp": 15, "power": 85, "accuracy": 85, "gen": 3} ,
{"name": "Sand Tomb", "type": "Ground", "category": "Physical", "contest": "Clever", "pp": 15, "power": 35, "accuracy": 35, "gen": 3} ,
{"name": "Sheer Cold", "type": "Ice", "category": "Special", "contest": "Beautiful", "pp": 5, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Muddy Water", "type": "Water", "category": "Special", "contest": "Tough", "pp": 10, "power": 90, "accuracy": 90, "gen": 3} ,
{"name": "Bullet Seed", "type": "Grass", "category": "Physical", "contest": "Cool", "pp": 30, "power": 25, "accuracy": 25, "gen": 3} ,
{"name": "Aerial Ace", "type": "Flying", "category": "Physical", "contest": "Cool", "pp": 20, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Icicle Spear", "type": "Ice", "category": "Physical", "contest": "Beautiful", "pp": 30, "power": 25, "accuracy": 25, "gen": 3} ,
{"name": "Iron Defense", "type": "Steel", "category": "Status", "contest": "Tough", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Block", "type": "Normal", "category": "Status", "contest": "Cute", "pp": 5, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Howl", "type": "Normal", "category": "Status", "contest": "Cool", "pp": 40, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Dragon Claw", "type": "Dragon", "category": "Physical", "contest": "Cool", "pp": 15, "power": 80, "accuracy": 80, "gen": 3} ,
{"name": "Frenzy Plant", "type": "Grass", "category": "Special", "contest": "Cool", "pp": 5, "power": 150, "accuracy": 150, "gen": 3} ,
{"name": "Bulk Up", "type": "Fighting", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Bounce", "type": "Flying", "category": "Physical", "contest": "Cute", "pp": 5, "power": 85, "accuracy": 85, "gen": 3} ,
{"name": "Mud Shot", "type": "Ground", "category": "Special", "contest": "Tough", "pp": 15, "power": 55, "accuracy": 55, "gen": 3} ,
{"name": "Poison Tail", "type": "Poison", "category": "Physical", "contest": "Clever", "pp": 25, "power": 50, "accuracy": 50, "gen": 3} ,
{"name": "Covet", "type": "Normal", "category": "Physical", "contest": "Cute", "pp": 25, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Volt Tackle", "type": "Electric", "category": "Physical", "contest": "Cool", "pp": 15, "power": 120, "accuracy": 120, "gen": 3} ,
{"name": "Magical Leaf", "type": "Grass", "category": "Special", "contest": "Beautiful", "pp": 20, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Water Sport", "type": "Water", "category": "Status", "contest": "Cute", "pp": 15, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Calm Mind", "type": "Psychic", "category": "Status", "contest": "Clever", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Leaf Blade", "type": "Grass", "category": "Physical", "contest": "Cool", "pp": 15, "power": 90, "accuracy": 90, "gen": 3} ,
{"name": "Dragon Dance", "type": "Dragon", "category": "Status", "contest": "Cool", "pp": 20, "power": -1, "accuracy": -1, "gen": 3} ,
{"name": "Rock Blast", "type": "Rock", "category": "Physical", "contest": "Tough", "pp": 10, "power": 25, "accuracy": 25, "gen": 3} ,
{"name": "Shock Wave", "type": "Electric", "category": "Special", "contest": "Cool", "pp": 20, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Water Pulse", "type": "Water", "category": "Special", "contest": "Beautiful", "pp": 20, "power": 60, "accuracy": 60, "gen": 3} ,
{"name": "Doom Desire", "type": "Steel", "category": "Special", "contest": "Beautiful", "pp": 5, "power": 140, "accuracy": 140, "gen": 3} ,
{"name": "Psycho Boost", "type": "Psychic", "category": "Special", "contest": "Clever", "pp": 5, "power": 140, "accuracy": 140, "gen": 3} ];
