exports.pokemon_types = [ [], ["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Fire"] ,
["Fire"] ,
["Fire", "Flying"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Bug"] ,
["Bug"] ,
["Bug", "Flying"] ,
["Bug", "Poison"] ,
["Bug", "Poison"] ,
["Bug", "Poison"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Normal"] ,
["Normal"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Poison"] ,
["Poison"] ,
["Electric"] ,
["Electric"] ,
["Ground"] ,
["Ground"] ,
["Poison"] ,
["Poison"] ,
["Poison", "Ground"] ,
["Poison"] ,
["Poison"] ,
["Poison", "Ground"] ,
["Normal"] ,
["Normal"] ,
["Fire"] ,
["Fire"] ,
["Normal"] ,
["Normal"] ,
["Poison", "Flying"] ,
["Poison", "Flying"] ,
["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Bug", "Grass"] ,
["Bug", "Grass"] ,
["Bug", "Poison"] ,
["Bug", "Poison"] ,
["Ground"] ,
["Ground"] ,
["Normal"] ,
["Normal"] ,
["Water"] ,
["Water"] ,
["Fighting"] ,
["Fighting"] ,
["Fire"] ,
["Fire"] ,
["Water"] ,
["Water"] ,
["Water", "Fighting"] ,
["Psychic"] ,
["Psychic"] ,
["Psychic"] ,
["Fighting"] ,
["Fighting"] ,
["Fighting"] ,
["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Grass", "Poison"] ,
["Water", "Poison"] ,
["Water", "Poison"] ,
["Rock", "Ground"] ,
["Rock", "Ground"] ,
["Rock", "Ground"] ,
["Fire"] ,
["Fire"] ,
["Water", "Psychic"] ,
["Water", "Psychic"] ,
["Electric", "Steel"] ,
["Electric", "Steel"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Water"] ,
["Water", "Ice"] ,
["Poison"] ,
["Poison"] ,
["Water"] ,
["Water", "Ice"] ,
["Ghost", "Poison"] ,
["Ghost", "Poison"] ,
["Ghost", "Poison"] ,
["Rock", "Ground"] ,
["Psychic"] ,
["Psychic"] ,
["Water"] ,
["Water"] ,
["Electric"] ,
["Electric"] ,
["Grass", "Psychic"] ,
["Grass", "Psychic"] ,
["Ground"] ,
["Ground"] ,
["Fighting"] ,
["Fighting"] ,
["Normal"] ,
["Poison"] ,
["Poison"] ,
["Ground", "Rock"] ,
["Ground", "Rock"] ,
["Normal"] ,
["Grass"] ,
["Normal"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Water", "Psychic"] ,
["Psychic"] ,
["Bug", "Flying"] ,
["Ice", "Psychic"] ,
["Electric"] ,
["Fire"] ,
["Bug"] ,
["Normal"] ,
["Water"] ,
["Water", "Flying"] ,
["Water", "Ice"] ,
["Normal"] ,
["Normal"] ,
["Water"] ,
["Electric"] ,
["Fire"] ,
["Normal"] ,
["Rock", "Water"] ,
["Rock", "Water"] ,
["Rock", "Water"] ,
["Rock", "Water"] ,
["Rock", "Flying"] ,
["Normal"] ,
["Ice", "Flying"] ,
["Electric", "Flying"] ,
["Fire", "Flying"] ,
["Dragon"] ,
["Dragon"] ,
["Dragon", "Flying"] ,
["Psychic"] ,
["Psychic"] ,
["Grass"] ,
["Grass"] ,
["Grass"] ,
["Fire"] ,
["Fire"] ,
["Fire"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Normal"] ,
["Normal"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Bug", "Flying"] ,
["Bug", "Flying"] ,
["Bug", "Poison"] ,
["Bug", "Poison"] ,
["Poison", "Flying"] ,
["Water", "Electric"] ,
["Water", "Electric"] ,
["Electric"] ,
["Normal"] ,
["Normal"] ,
["Normal"] ,
["Normal", "Flying"] ,
["Psychic", "Flying"] ,
["Psychic", "Flying"] ,
["Electric"] ,
["Electric"] ,
["Electric"] ,
["Grass"] ,
["Water"] ,
["Water"] ,
["Rock"] ,
["Water"] ,
["Grass", "Flying"] ,
["Grass", "Flying"] ,
["Grass", "Flying"] ,
["Normal"] ,
["Grass"] ,
["Grass"] ,
["Bug", "Flying"] ,
["Water", "Ground"] ,
["Water", "Ground"] ,
["Psychic"] ,
["Dark"] ,
["Dark", "Flying"] ,
["Water", "Psychic"] ,
["Ghost"] ,
["Psychic"] ,
["Psychic"] ,
["Normal", "Psychic"] ,
["Bug"] ,
["Bug", "Steel"] ,
["Normal"] ,
["Ground", "Flying"] ,
["Steel", "Ground"] ,
["Normal"] ,
["Normal"] ,
["Water", "Poison"] ,
["Bug", "Steel"] ,
["Bug", "Rock"] ,
["Bug", "Fighting"] ,
["Dark", "Ice"] ,
["Normal"] ,
["Normal"] ,
["Fire"] ,
["Fire", "Rock"] ,
["Ice", "Ground"] ,
["Ice", "Ground"] ,
["Water", "Rock"] ,
["Water"] ,
["Water"] ,
["Ice", "Flying"] ,
["Water", "Flying"] ,
["Steel", "Flying"] ,
["Dark", "Fire"] ,
["Dark", "Fire"] ,
["Water", "Dragon"] ,
["Ground"] ,
["Ground"] ,
["Normal"] ,
["Normal"] ,
["Normal"] ,
["Fighting"] ,
["Fighting"] ,
["Ice", "Psychic"] ,
["Electric"] ,
["Fire"] ,
["Normal"] ,
["Normal"] ,
["Electric"] ,
["Fire"] ,
["Water"] ,
["Rock", "Ground"] ,
["Rock", "Ground"] ,
["Rock", "Dark"] ,
["Psychic", "Flying"] ,
["Fire", "Flying"] ,
["Psychic", "Grass"] ,
["Grass"] ,
["Grass"] ,
["Grass"] ,
["Fire"] ,
["Fire", "Fighting"] ,
["Fire", "Fighting"] ,
["Water"] ,
["Water", "Ground"] ,
["Water", "Ground"] ,
["Dark"] ,
["Dark"] ,
["Normal"] ,
["Normal"] ,
["Bug"] ,
["Bug"] ,
["Bug", "Flying"] ,
["Bug"] ,
["Bug", "Poison"] ,
["Water", "Grass"] ,
["Water", "Grass"] ,
["Water", "Grass"] ,
["Grass"] ,
["Grass", "Dark"] ,
["Grass", "Dark"] ,
["Normal", "Flying"] ,
["Normal", "Flying"] ,
["Water", "Flying"] ,
["Water", "Flying"] ,
["Psychic"] ,
["Psychic"] ,
["Psychic"] ,
["Bug", "Water"] ,
["Bug", "Flying"] ,
["Grass"] ,
["Grass", "Fighting"] ,
["Normal"] ,
["Normal"] ,
["Normal"] ,
["Bug", "Ground"] ,
["Bug", "Flying"] ,
["Bug", "Ghost"] ,
["Normal"] ,
["Normal"] ,
["Normal"] ,
["Fighting"] ,
["Fighting"] ,
["Normal"] ,
["Rock"] ,
["Normal"] ,
["Normal"] ,
["Dark", "Ghost"] ,
["Steel"] ,
["Steel", "Rock"] ,
["Steel", "Rock"] ,
["Steel", "Rock"] ,
["Fighting", "Psychic"] ,
["Fighting", "Psychic"] ,
["Electric"] ,
["Electric"] ,
["Electric"] ,
["Electric"] ,
["Bug"] ,
["Bug"] ,
["Grass", "Poison"] ,
["Poison"] ,
["Poison"] ,
["Water", "Dark"] ,
["Water", "Dark"] ,
["Water"] ,
["Water"] ,
["Fire", "Ground"] ,
["Fire", "Ground"] ,
["Fire"] ,
["Psychic"] ,
["Psychic"] ,
["Normal"] ,
["Ground"] ,
["Ground", "Dragon"] ,
["Ground", "Dragon"] ,
["Grass"] ,
["Grass", "Dark"] ,
["Normal", "Flying"] ,
["Dragon", "Flying"] ,
["Normal"] ,
["Poison"] ,
["Rock", "Psychic"] ,
["Rock", "Psychic"] ,
["Water", "Ground"] ,
["Water", "Ground"] ,
["Water"] ,
["Water", "Dark"] ,
["Ground", "Psychic"] ,
["Ground", "Psychic"] ,
["Rock", "Grass"] ,
["Rock", "Grass"] ,
["Rock", "Bug"] ,
["Rock", "Bug"] ,
["Water"] ,
["Water"] ,
["Normal"] ,
["Normal"] ,
["Ghost"] ,
["Ghost"] ,
["Ghost"] ,
["Ghost"] ,
["Grass", "Flying"] ,
["Psychic"] ,
["Dark"] ,
["Psychic"] ,
["Ice"] ,
["Ice"] ,
["Ice", "Water"] ,
["Ice", "Water"] ,
["Ice", "Water"] ,
["Water"] ,
["Water"] ,
["Water"] ,
["Water", "Rock"] ,
["Water"] ,
["Dragon"] ,
["Dragon"] ,
["Dragon", "Flying"] ,
["Steel", "Psychic"] ,
["Steel", "Psychic"] ,
["Steel", "Psychic"] ,
["Rock"] ,
["Ice"] ,
["Steel"] ,
["Dragon", "Psychic"] ,
["Dragon", "Psychic"] ,
["Water"] ,
["Ground"] ,
["Dragon", "Flying"] ,
["Steel", "Psychic"] ,
["Psychic"] ];
